insta/routes/web.php
<?php
//use App\Mail\WelcomeMail;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::get('/email', function () {
//    return new WelcomeMail();
//});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/user', 'userController');
Route::resource('/post', 'PostController');
Route::get('/comment/{id}', 'PostController@comment')->name('comment');
Route::post('/likes/{id}', 'PostController@likes')->name('likes');
Route::post('/filter/{id}', 'PostController@filter')->name('filter');
Route::get('/filter/{id}', 'PostController@filter')->name('filter');
Route::get('/imgPostType', 'PostController@imgPostType')->name('imgPostType');
Route::get('/videoPostType', 'PostController@videoPostType')->name('videoPostType');

insta/app/Post.php
<?php

namespace App;

use App\Comment;
use App\User;
use Illuminate\Database\Eloquent\Model;


class   Post extends Model
{
    public function users()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function usr()
    {
        return $this->hasMany(User::class);
    }

    public function getCoverImgAttributes($value)
    {

        return url('/storage/' . $value);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
//    public function usr(){
//        return $this->belongsToMany(User::class);
//    }
    protected $fillable = [
        'user_id', 'title', 'post_url','post_type'
    ];
}

insta/app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\User;
use App\Post;
use App\Country;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        if (\Auth::check()) {
            $data = Post::orderBy('created_at', 'desc')->get();

            $countries = Country::all();
//          dd($countries);
//            return view('post.post', compact('data','countries'));
            return view('post.post')->with('data', $data)
                ->with('countries', $countries);


//        } else {
//            return redirect('login');
//        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {


        return view('post.add_post');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => ['required', 'string'],
            'post_url' => ['required', 'max:50000', 'mimes:jpeg,jpg,png,bmp,mpv4,mov,ogg,gif'],

        ]);
        $image_type = ['jpeg','png','jpg','gif'];
        $image = $request->file('post_url');
        $originalname = uniqid('Img', 10) . '.' . $image->getClientOriginalExtension();
//        $path = in_array($originalname,$image_type)->storeAs('/post_url', $originalname, 'public');
      $path = $image->storeAs('/post_url', $originalname, 'public');
       $data = Post::create([

            'user_id' => Auth::id(),
            'title' => $request->title,
            'post_url' => $path,
            'post_type'=> in_array($originalname,$image_type) ? 'image' : 'video'
        ]);


//        $data = new Post();
//        $data->user_id = Auth::id();
//        $data->title = $request->title;
//        $image = $request->file('post_url');
//        $originalname = uniqid('Img',10) .'.'.$image->getClientOriginalExtension();
//        $path = $image->storeAs('/userimagepost',$originalname,'public');
//        $data->post_url = $path;
//        $data->save();
        return redirect()->route('post.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Post::find($id);
        $data->delete();
        return redirect()->route('post.index')->with('success', 'Data Deleted');
    }

    public function comment(Request $request, $id)
    {
//        $data = new Comment();
//        $data->user_id = Auth::id();
//        $data->post_id = $id;
//        $data->comments = $request->comment;
//        $data->save();
//        return redirect()->route('post.index');

        $data = Comment::create([
            'user_id' => Auth::id(),
            'post_id' => $id,
            'comments' => $request->comment

        ]);
//        $data->save();
        return redirect()->route('post.index');

    }

    public function likes($id)
    {
        $data = Post::find($id);
        if ($data->likes == 1) {
            $data->likes = 0;
        } else {
            $data->likes = 1;
        }
        $data->save();
        return redirect()->route('post.index');
    }

    public function filter($id)
    {
        $filter = Country::find($id)->posts;
        return view('post.country_post', compact('filter'));

    }
    public function imgPostType(){

        $postType = Post::all()->where('post_type' ,'=', 'image');

            return view('post.imagepost', compact('postType'));

//        else{
//            return view('post.videopost',compact('postType'));
//        }

//        return redirect()->route('post.index');
    }
    public function videoPostType()
    {

        $postType = Post::all()->where('post_type', '=', 'video');

        return view('post.videopost', compact('postType'));
    }
}

insta/resources/views/post/add_post.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Add Post') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('post.store') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Title') }}</label>

                                <div class="col-md-6">
                                    <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}" autocomplete="name" autofocus>

                                    @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="post_url" class="col-md-4 col-form-label text-md-right">Post:</label>
                                <input type="file" class="form-control ml-3 col-md-4 col-form-label text-md-right @error('post_url') is-invalid @enderror" id="post_url" name="post_url">
                                @error('post_url')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Add_Post') }}
                                    </button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

insta/resources/views/post/country_post.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-5">
        @foreach($filter as $filter)
            <div class="card-body">
                <div class="card align-items-center">

                    <img src="{{url('/storage/'.$filter->post_url)}}" width="100% ;" height="400px;">

                    <form method="Post" action="{{url("comment/{$filter->id}")}}">
                        @csrf
                        @method('get')
                        @if(Auth::id()!= $filter->user_id)
                        <input type="text" name="comment"  placeholder="comment..." class="mt-2"><br>
                        <input type="submit" class="btn btn-primary mt-2" value="Comment">
                        @endif
                    </form>


                        @foreach($filter->comments as $comment)

                            <b><label>comment by :{{$comment->user->name}}</label></b>
                            {{$comment->comments}}

                        @endforeach

                    @if($filter->likes == 1)
                        <form action="{{ route('likes', $filter->id) }}" method="POST">
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-secondary" name="likes" value="0">dislike</button>
                        </form>
                    @else
                        <form action="{{ route('likes', $filter->id) }}" method="POST">
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-primary" name="likes" value="1">like</button>
                        </form>
                    @endif

                    @if(Auth::id() == $filter->user_id)
                        <form method="post" class="delete_form" action="/filter/{{$filter->id}}">
                            @csrf
                            <input type="hidden" name="_method" value="DELETE" />
                            <button type="submit" class="btn btn-danger brn-large">Delete</button>
                        </form>
                    @endif


                </div>
            </div>
            @endforeach
            </div>
        </div>
    </div>
@endsection

insta/resources/views/post/imagepost.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-5">
                @foreach($postType as $postType)
                    <div class="card-body">
                        <div class="card align-items-center">

                            <img src="{{url('/storage/'.$postType->post_url)}}" width="100% ;" height="400px;">


                            <form method="Post" action="{{url("comment/{$postType->id}")}}">
                                @csrf
                                @method('get')
                                @if(Auth::id()!= $postType->user_id)
                                    <input type="text" name="comment"  placeholder="comment..." class="mt-2"><br>
                                    <input type="submit" class="btn btn-primary mt-2" value="Comment">
                                @endif
                            </form>


                            @foreach($postType->comments as $comment)

                                <b><label>comment by :{{$comment->user->name}}</label></b>
                                {{$comment->comments}}

                            @endforeach

                            @if($postType->likes == 1)
                                <form action="{{ route('likes', $postType->id) }}" method="POST">
                                    {{ csrf_field() }}
                                    <button type="submit" class="btn btn-secondary" name="likes" value="0">dislike</button>
                                </form>
                            @else
                                <form action="{{ route('likes', $postType->id) }}" method="POST">
                                    {{ csrf_field() }}
                                    <button type="submit" class="btn btn-primary" name="likes" value="1">like</button>
                                </form>
                            @endif

                            @if(Auth::id() == $postType->user_id)
                                <form method="post" class="delete_form" action="/imgPostType/{{$postType->id}}">
                                    @csrf
                                    <input type="hidden" name="_method" value="DELETE" />
                                    <button type="submit" class="btn btn-danger brn-large">Delete</button>
                                </form>
                            @endif


                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
@endsection

insta/resources/views/post/post.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-5">



{{--                <div class="form-group row">--}}
{{--                    <label for="country_name" class="col-md-4 col-form-label text-md-right">Country</label>--}}
{{--                    <select class="custom-select col-md-4 ml-3 col-form-label text-md-right @error('') is-invalid @enderror" name="country_name" id="country_name">--}}
{{--                        <option hidden value="">Country</option>--}}
{{--                        @foreach($countries as $countries)--}}

{{--                            <form method="POST" action="{{url("/filter/{$countries->id}")}}" enctype="multipart/form-data">--}}
{{--                                @csrf--}}
{{--                                @method("get")--}}
{{--                                <option value="{{ $countries->id }}">{{ $countries->country_name }}</option>--}}
{{--                            </form>--}}
{{--                        @endforeach--}}
{{--                    </select>--}}
{{--                </div>--}}



                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle form-control" type="button"
                            id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">
                        Country
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        @foreach($countries as $countries)
                            <form method="post" class="form" action="{{url("/filter/{$countries->id}")}}">
                                @csrf
                                @method('get')
                                <button class="btn btn-outline-primary form-control" type="submit"
                                        value="{{ $countries->id }}">{{ $countries->country_name }}</button>
                            </form>
                        @endforeach
                    </div>
                </div>

                <div class="dropdown">

                    <form method="post" class="form" action="{{route('imgPostType')}}">
                        @csrf
                        @method('get')
                        <button class="btn btn-outline-primary form-control" type="submit">Images</button>
                    </form>
                </div>

                <div class="dropdown">

                    <form method="post" class="form" action="{{route('videoPostType')}}">
                        @csrf
                        @method('get')
                        <button class="btn btn-outline-primary form-control" type="submit">video</button>
                    </form>
                </div>


            @foreach($data as $data)
                    <div class="card-body">
                <div class="card align-items-center">






                    <img src="{{url('/storage/'.$data->post_url)}}" width="100% ;" height="400px;">



                    <form method="Post" action="{{url("comment/{$data->id}")}}">
                        @csrf
                        @method('get')
                        @if(Auth::id()!= $data->user_id)
                        <input type="text" name="comment"  placeholder="comment..." class="mt-2"><br>
                        <input type="submit" class="btn btn-primary mt-2" value="Comment">

                        @endif
                    </form>


                         @foreach($data->comments as $comment)
                        <b><label>comment by :{{$comment->user->name}}</label></b>
                        {{$comment->comments}}

                         @endforeach
                    @if($data->likes == 1)
                        <form action="{{ route('likes', $data->id) }}" method="POST">
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-primary" name="likes" value="1">like</button>
                        </form>
                    @else
                        <form action="{{ route('likes', $data->id) }}" method="POST">
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-secondary" name="likes" value="0">dislike</button>
                        </form>
                    @endif

                        @if(Auth::id() == $data->user_id)
                        <form method="post" class="delete_form" action="/post/{{$data->id}}">
                            @csrf
                            <input type="hidden" name="_method" value="DELETE" />
                            <button type="submit" class="btn btn-danger brn-large">Delete</button>
                        </form>
                    @endif

                </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
@endsection

insta/resources/views/post/videopost.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-5">
                @foreach($postType as $postType)
                    <div class="card-body">
                        <div class="card align-items-center">

                            <img src="{{url('/storage/'.$postType->post_url)}}" width="100% ;" height="400px;">

                            <form method="Post" action="{{url("comment/{$postType->id}")}}">
                                @csrf
                                @method('get')
                                @if(Auth::id()!= $postType->user_id)
                                    <input type="text" name="comment"  placeholder="comment..." class="mt-2"><br>
                                    <input type="submit" class="btn btn-primary mt-2" value="Comment">
                                @endif
                            </form>


                            @foreach($postType->comments as $comment)

                                <b><label>comment by :{{$comment->user->name}}</label></b>
                                {{$comment->comments}}

                            @endforeach

                            @if($postType->likes == 1)
                                <form action="{{ route('likes', $postType->id) }}" method="POST">
                                    {{ csrf_field() }}
                                    <button type="submit" class="btn btn-secondary" name="likes" value="0">dislike</button>
                                </form>
                            @else
                                <form action="{{ route('likes', $postType->id) }}" method="POST">
                                    {{ csrf_field() }}
                                    <button type="submit" class="btn btn-primary" name="likes" value="1">like</button>
                                </form>
                            @endif

                            @if(Auth::id() == $postType->user_id)
                                <form method="post" class="delete_form" action="/videoPostType/{{$postType->id}}">
                                    @csrf
                                    <input type="hidden" name="_method" value="DELETE" />
                                    <button type="submit" class="btn btn-danger brn-large">Delete</button>
                                </form>
                            @endif



                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
@endsection