insta/routes/web.php
<?php
//use App\Mail\WelcomeMail;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::get('/email', function () {
//    return new WelcomeMail();
//});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/user', 'userController');
Route::resource('/post', 'PostController');
Route::get('/comment/{id}', 'PostController@comment')->name('comment');
Route::post('/likes/{id}', 'PostController@likes')->name('likes');
Route::post('/filter/{id}', 'PostController@filter')->name('filter');
Route::get('/filter/{id}', 'PostController@filter')->name('filter');
Route::get('/imgPostType', 'PostController@imgPostType')->name('imgPostType');
Route::get('/videoPostType', 'PostController@videoPostType')->name('videoPostType');

insta/resources/views/edit_user.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Edit Profile') }}</div>

                    <div class="card-body">
                        {{--                        <form method="POST" action="{{ route('register') }}" enctype="multipart/form-data">--}}
                        <form action={{route('user.update',$data->id)}} method="post" enctype="multipart/form-data">
                            {{--        <input type="hidden" name="_token" value="{{csrf_token()}}">--}}
                            {{csrf_field()}}
                            @method('PATCH')
                            <div class="form-group row">
                                <label for="country_name" class="col-md-4 col-form-label text-md-right">Country</label>
                                <select class="custom-select col-md-4 ml-3 col-form-label text-md-right @error('') is-invalid @enderror"  name="country_name" id="country_name">
                                    <option hidden>Country</option>
                                    @foreach($countries as $country)
                                        <option value="{{ $country->id }}" {{ $data->country_id==$country->id?'selected':'' }}>{{ $country->country_name }}</option>
                                    @endforeach
                                </select>
                                @error('country_name')
                                <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                                 </span>
                                @enderror
                            </div>
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{$data->name}}" autocomplete="name" >

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="username" class="col-md-4 col-form-label text-md-right">{{ __('UserName') }}</label>

                                <div class="col-md-6">
                                    <input id="username" type="text" class="form-control @error('username') is-invalid @enderror" name="username" value="{{$data->username}}"  autocomplete="username" >

                                    @error('username')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{$data->email}}"  autocomplete="email">

                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="dob" class="col-md-4 col-form-label text-md-right">{{ __('Date of Birth') }}</label>

                                <div class="col-md-6">
                                    <input id="dob" type="date" class="form-control @error('dob') is-invalid @enderror" name="dob" value="{{$data->dob}}"  autocomplete="dob" >

                                    @error('dob')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                @if ("/storage/{{ $data->images }}")
                                    <img src="{{ $data->image }}">
                                @else
                                    <p>No image found</p>
                                @endif
                                <label for="profile_pic" class="col-md-4 col-form-label text-md-right">{{ __('profile_pic') }}</label>

                                <div class="col-md-6">
                                    <input id="profile_pic" type="file" class="form-control @error('profile_pic') is-invalid @enderror" name="profile_pic" value="{{ $data->profile_pic}}"  autocomplete="profile_pic">

                                    @error('profile_pic')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('update') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

insta/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

insta/resources/views/user_show.blade.php
@extends('layouts.app')
<meta charset="UTF-8">
<meta name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">

<title>Show</title>
@section('content')
    <div class="container">

{{--        <table class="table">--}}
{{--            <thead>--}}
{{--            <tr>--}}
{{--                <th scope="col">Country</th>--}}
{{--                <th scope="col">Name</th>--}}
{{--                <th scope="col">UserName</th>--}}
{{--                <th scope="col">Email</th>--}}
{{--                <th scope="col">Date_of_birth</th>--}}
{{--                <th scope="col">profile_pic</th>--}}
{{--                <th scope="col">Edit</th>--}}
{{--                <th scope="col">Delete</th>--}}
{{--            </tr>--}}
{{--            </thead>--}}
{{--            <tbody>--}}

{{--                <tr>--}}

{{--                    <td>{{$data->country_id}}</td>--}}
{{--                    <td>{{$data->name}}</td>--}}
{{--                    <td>{{$data->username}}</td>--}}
{{--                    <td>{{$data->email}}</td>--}}
{{--                    <td>{{$data->dob}}</td>--}}
{{--                    <td><img src="{{url('/storage/'.$data->profile_pic)}}" width="100px;" height="100px;"></td>--}}
{{--                    <td><a type="button" class="btn btn-success" href="/user/{{$data->id}}/edit">Edit</a></td>--}}
{{--                    <td>--}}
{{--                        <form method="post" class="delete_form" action="/user/{{$data->id}}">--}}
{{--                            @csrf--}}
{{--                            <input type="hidden" name="_method" value="DELETE" />--}}
{{--                            <button type="submit" class="btn btn-danger">Delete</button>--}}
{{--                        </form>--}}
{{--                    </td>--}}

{{--                </tr>--}}

{{--            </tbody>--}}
{{--        </table>--}}


        <div class="card border-dark col-md-8 offset-md-4" style="width:300px">
            <div class="card-header">My Profile</div>
                 <div class="card-body">
                <p><strong>Profile pic :</strong><img src="{{url('/storage/'.$data->profile_pic)}}" class="mt-3 ml-3" width="150px;" height="150px;"></p>
                <p><strong class="mr-5">Country:</strong> {{$data->country->country_name}}</p>
                <p><strong class="mr-5">Name :</strong> {{$data->name}}</p>
                <p><strong class="mr-3">UserName :</strong>{{$data->username}}</p>
                <p><strong class="mr-4">Email :</strong>{{$data->email}}</p>
                <p><strong class="mr-3">Date_of_Birth :</strong>{{$data->dob}}</p>
                <a type="button" class="btn btn-success" href="/user/{{$data->id}}/edit">Edit</a>
                </div>

    </div>
        </div>
@endsection